version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.2

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov=simpleblog
#  deploy:
#    docker:
#      - image: circleci/python:3.9.2
#    steps:
#      - attach_workspace:
#          at: ~/repo
#      - add_ssh_keys
      - run:
          name: deploy
          command: |
            ssh -o StrictHostKeyChecking=no circleci@54.175.198.73:~/crudSystem exit
            echo '54.175.198.73 ecdsa-sha2-nistp256 AAAAB3NzaC1yc2EAAAADAQABAAABgQC8By7uAAcV2Pnm/WffP7OWzH16sJM+ZuKHb16XxKcK0kotPLh8OC4QbUqpyJBBvLLUYfzfVNQSuCguHjSLyIGDz8tfbZ7OP6Xbt+G74+9h6ItIcBEmg1O13dK+mnv349sKXiTOBPjka6m54Ue8rbm3omnxtzAo1E7p+WR8L2PUOCq2SaBYeLd/H1VvYjlDnqjKCvT9rop8IpJpoJ2ywU9+Ucyjf5U9F2pf9FqMRKTqpR6aHprbj/cFMNpWWh0GMMh1Y9/nv8sk+OoPUtG0p0YVA7tJ0eyxQmuSUS9WYA0rKEpHzlDyLDIDD1rss3U3sscy3MFxokko4Mi2mFWomizNxfXxMzsafQj227lgRt/Abyil0Qm1y6s+aQYLX2r72WwNT9moPUczIyt82Bwtx65GmlakI4A6VUmo8JkVElrVHAUz4qy1J64xy4VSd15+EfUBxVZ3BWtr0HCoSdb7NkrGRhUGz7UznjPpoSXmmKID7kuRdvyZz9fIv/wZnKw50nE=' >> ~/.ssh/known_hosts
            scp -r ~/repo circleci@54.175.198.73:~/crudSystem
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
